### ISSUE TITLE
Zombie's in the house

### ISSUE THREAD

**Issue by jas-williams** [Wheaties466/helium_miner_scripts#20]
It seems that if the miner process crashes within the docker it restarts but zombies occur the work around is to add --init to the docker run command to do this the docker creation command needs to include --init like this

docker run -d --init --env REGION_OVERRIDE=$REGION --restart always --publish $GWPORT:$GWPORT/udp --publish $MINERPORT:$MINERPORT/tcp --name $MINER --mount type=bind,source=$DA$

this was seen by othes in the diy thread on discord

https://discordapp.com/channels/404106811252408320/730246424666832947/770990904861261834

**Comment by miqueet** [comment]
resolved in the following commit.

https://github.com/Wheaties466/helium_miner_scripts/commit/1fa69f6d1934580d01657f7b01a2aef452be85af
