### ISSUE TITLE
miner_latest.sh can't get the newest firmware version.

### ISSUE THREAD

**Issue by bangdracaena** [Wheaties466/helium_miner_scripts#37]
Error: No such container: miner
parse error: Invalid numeric literal at line 1, column 10

**Comment by miqueet** [comment]
if I change this url to this https://quay.io/repository/team-helium/miner?tab=tags Does it work?

**Comment by bangdracaena** [comment]
> I solved by using wget replacing for curl, thanks

**Comment by miqueet** [comment]
@bangdracaena does the script need to be adjusted or changed?
